image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        deployment: staging
        script:
          - echo "Deploying to Radio Server"
          - cat ./deploy_web.sh | ssh -tt ubuntu@51.210.246.200
          - echo "Finished"
